name: Build and Release Update Package

on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Build package
      run: bash rpi/build-package.sh
    - name: "Upload artifact: release tarball"
      with:
        name: release
        path: rpi/out
        retention-days: 1
    - name: "Upload artifact: site"
      uses: actions/upload-artifact@v4.3.3
      with:
        name: github-pages
        path: site
        retention-days: 1
    - name: Deploy site
      uses: actions/deploy-pages@v4.0.5
